### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dreamskill-Prog** [QuyAnh2005/FragmentVC-Japanese#1]
Hello, How are you?
I am a beginner to intend learning about AI(voice).
I am going to convert any voice into any voice in Japanese.
So, it downloads and then ran it. 
And it had been imported the source and target music file and then it clicked "Submit".
But the error is corrupted. I do not know why the error is ocured correctly.
And the modules were not installed well.
Could you help me, please?
Thank you.

python == 3.8.4
pip 24.0

![error_1](https://github.com/QuyAnh2005/FragmentVC-Japanese/assets/149992522/19bba63a-085f-4d0a-88f1-cb707b29dad2)

---------------------- Error(in CMD command window)--------------------

Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

F:\Other\Voice_Clone\main>py app.py
C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
[INFO] Wav2Vec is loaded from ./pretrained/wav2vec_small.pt
C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\transformer.py:286: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer was not TransformerEncoderLayer
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
[INFO] FragmentVC is loaded from ./pretrained/fragment.pt
[INFO] Vocoder is loaded from ./pretrained/vocoder.pt
Running on local URL:  http://127.0.0.1:7860
2024-02-24 21:13:42 | INFO | httpx | HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
2024-02-24 21:13:42 | INFO | httpx | HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"
2024-02-24 21:13:42 | INFO | httpx | HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
2024-02-24 21:13:44 | INFO | httpx | HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
2024-02-24 21:13:45 | INFO | httpx | HTTP Request: POST https://api.gradio.app/gradio-initiated-analytics/ "HTTP/1.1 200 OK"
2024-02-24 21:13:48 | INFO | httpx | HTTP Request: GET https://api.gradio.app/v2/tunnel-request "HTTP/1.1 200 OK"
Running on public URL: https://638ba5059cd4114adb.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
2024-02-24 21:13:50 | INFO | httpx | HTTP Request: POST https://api.gradio.app/gradio-launched-telemetry/ "HTTP/1.1 200 OK"
2024-02-24 21:14:36 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2024-02-24 21:14:49 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
1
Traceback (most recent call last):
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\12-lsr\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 59, in voice_conversion
    sr, wav = target_audio
TypeError: cannot unpack non-iterable NoneType object

**Comment by QuyAnh2005** [comment]
Sorry for the late reply @Dreamskill-Prog
Did you install packages as in the `requirements.txt`?

**Comment by Dreamskill-Prog** [comment]
Hello
Thank you for your reply.

**Comment by Dreamskill-Prog** [comment]
Do my computer have GPU?

**Comment by QuyAnh2005** [comment]
Should use GPU. You can clone this project into google colab and run inference.

**Comment by Dreamskill-Prog** [comment]
Hello, you have s-k-y-p-e or t-e-l-e-g-r-a-m?

**Comment by Dreamskill-Prog** [comment]
What about the effect of this projects?
That is OK?

**Comment by Dreamskill-Prog** [comment]
I am sorry. what about Python version?

**Comment by QuyAnh2005** [comment]
I used Python 3.8. In this week, I'm quite busy. So I will run this project again on my local on the weekends. and reply you later.
It's OK? @Dreamskill-Prog

**Comment by Dreamskill-Prog** [comment]
Thank you really.
 I am sorry, what about the effect of this project and then could you give me skype or telegram address, please?

**Comment by QuyAnh2005** [comment]
It's my skype anhdq@wingsmob.vn @Dreamskill-Prog

**Comment by Dreamskill-Prog** [comment]
Thank you. I sent invitation.
